### ISSUE TITLE
ImportError: No module named flask.ext.script

### ISSUE THREAD

**Issue by Euphorbium** [imwilsonxu/fbone#26]
Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from flask.ext.script import Manager
ImportError: No module named flask.ext.script

I am getting this error, when I run fab d. What should I do?

**Comment by raowl** [comment]
something like that happened to me just now, realised it wasnt getting the virtualenv so added this step and worked fine:
no sudo needed, you are making a virtualenv inside this directory as your user, no need for root.

    git clone https://github.com/imwilsonxu/fbone.git fbone
    cd fbone
    fab setup
    . env/bin/activate
    fab d

**Comment by imwilsonxu** [comment]
Fix with 6ff899e7e8f8d5de7e55a0b8cb1ec749192798d7
`Flask-Script` is removed, use built-in cli instead.

**Comment by akshesh-innoplexus** [comment]
I installed without using `sudo` as suggested above somewhere in the discussion and everything works fine. Thanks.

**Comment by qninhks123** [comment]
---

**Comment by qninhks123** [comment]
|a|a|
|-|-|
|a|a|
