### ISSUE TITLE
setup instructions incomplete - assumes familiarity

### ISSUE THREAD

**Issue by paul-hammant** [imwilsonxu/fbone#39]
needed "brew install fabric" advice (etc).. and even then ...

$ fab setup 
[] Executing task 'setup'
[localhost] local: virtualenv env
/bin/sh: virtualenv: command not found

Fatal error: local() encountered an error (return code 127) while executing 'virtualenv env'

**Comment by no13bus** [comment]
type these in your shell:
```
pip install fabric
pip installl virtualenv
```
Is it ok?

**Comment by imwilsonxu** [comment]
Python / pip / fabric is pre-required.
