### ISSUE TITLE
ImportError: 'twill' package is required for Error

### ISSUE THREAD

**Issue by shulhi** [imwilsonxu/fbone#40]
I can't run the unit test using nose. I have installed `twill` through `pip install twill`. Is there such requirement for specific version?

I removed Twill altogether, and it is working fine except that the test always hang at `test_login`. Any hint on what is happening?

**Comment by mumas** [comment]
Hi,
I had the same problem on my mac 10.10.2. 

First, try to run python (env/bin/python) and check if you can import twill. I was having some problems even if I installed it with `pip install twill`

I ended up installing these packages:
pip install twill Flask-Testing lxml requests cssselect

leading to pip freeze:

Babel==1.3
Fabric==1.10.1
Flask==0.10.1
Flask-Babel==0.9
Flask-Cache==0.13.1
Flask-Login==0.2.11
Flask-Mail==0.9.1
Flask-OpenID==1.2.4
Flask-SQLAlchemy==2.0
Flask-Script==2.0.5
Flask-Testing==0.4.2
Flask-WTF==0.11
Jinja2==2.7.3
MarkupSafe==0.23
MySQL-python==1.2.5
SQLAlchemy==0.9.8
WTForms==2.0.2
Werkzeug==0.10.1
blinker==1.3
cssselect==0.9.1
ecdsa==0.13
fbone==0.1
itsdangerous==0.24
lxml==3.4.2
nose==1.3.4
paramiko==1.15.2
pycrypto==2.6.1
python-openid==2.2.5
pytz==2014.10
requests==2.5.1
speaklater==1.3
twill==1.8.0
wsgiref==0.1.2

Now it works fine (except one warning of sqlalchemy)

**Comment by shulhi** [comment]
I solved it by adding `db.session.remove()` during test `tearDown`. Somehow, the session does not get removed automatically.

**Comment by imwilsonxu** [comment]
Fix with 6ff899e7e8f8d5de7e55a0b8cb1ec749192798d7
