### ISSUE TITLE
Small bug in user/views.py.

### ISSUE THREAD

**Issue by gitmeister** [imwilsonxu/fbone#56]
>@user.route('/profile', methods=['GET', 'POST'])
>@login_required
>def profile():
>   form = ProfileForm(obj=current_user)
>   if form.validate_on_submit():
>      form.populate_obj(user)
>      user.update_at = get_current_time()
> ......

needs to be corrected to:

> @user.route('/profile', methods=['GET', 'POST'])
> @login_required
>  def profile():
>      form = ProfileForm(obj=current_user)
>      if form.validate_on_submit():
>         form.populate_obj(**_current_user_**)
>       **_current_user_**.update_at = get_current_time()
> ......

I'd do a "Pull Request" myself but i'm a noob at Git.

**Comment by benj02** [comment]
Made a pull req for this, #58
